# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [41]:
import numpy as np

#### Create an array of 10 zeros

In [42]:
arr = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Create an array of 10 ones

In [43]:
arr1 = np.array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### Create an array of 10 fives

In [44]:
arr5 = np.array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])


#### Create an array of the integers from 10 to 50

In [45]:
arr10_50 = np.arange(10, 51)
print(arr10_50)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

> Add blockquote



In [46]:
arr10_50_even = np.arange(10, 51, 2)
print(arr10_50_even)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [47]:
arr3x3 = np.arange(9).reshape(3, 3)
print(arr3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [48]:
arr3x3I = np.eye(3)
print(arr3x3I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [49]:
rand_num = np.random.rand()
rand_num

0.9203992482206604

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [50]:
num25 = np.random.randn(24)
num25_2 = np.abs(np.random.randn(24))
print(num25)
print(num25_2)

[-1.11623362 -0.4926253  -1.44167978  1.12440295  0.01587105  0.88738832
 -0.45897376  0.47494005 -0.03224047  1.62293261 -0.36755492  0.52720081
 -0.67776581 -1.00933147 -2.66629723 -0.96986137  0.92562385  0.61155365
  0.0363488   0.01263063 -0.6461603   0.68510366  0.60048979  0.10789716]
[0.38246796 1.03187959 0.84553738 1.99524442 0.33552991 0.36759062
 0.89510585 0.93145867 0.02370021 0.24840572 2.09863274 0.77635953
 0.162177   0.38295889 0.13053643 1.57055378 0.24089507 1.08894734
 0.30153448 0.00366964 0.2366796  1.27976089 0.23992004 0.04245418]


#### Create the following matrix:

In [51]:
matrix=np.linspace(0.01, 1, 100).reshape(10, 10)
matrix

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [52]:
arr_spaced = np.linspace(0, 1, 20)
arr_spaced

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [53]:
arr_a= np.arange(1,26).reshape(5,5)
arr_a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [54]:
arr_b= np.arange(12,27).reshape(3,5)
arr_b

array([[12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26]])

In [55]:
arr_c=20
arr_c

20

In [56]:
arr_d=np.arange(2,13,5).reshape(3,1)
arr_d

array([[ 2],
       [ 7],
       [12]])

In [57]:
arr_e=np.arange(21,26)
arr_e

array([21, 22, 23, 24, 25])

In [58]:
arr_f=np.arange(16,26).reshape(2,5)
arr_f

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# Great Job!