# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [ ]:
import numpy as np

#### Create an array of 10 zeros

In [ ]:
# arr = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0])
arr0 = np.zeros(10)
print(arr0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [ ]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [ ]:
print(np.full(10, 5))

[5 5 5 5 5 5 5 5 5 5]


#### Create an array of the integers from 10 to 50

In [ ]:
print(np.arange(10,51))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [ ]:
print(np.arange(10,51,2))

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
arr2 = np.arange(0,9)
print(arr2.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [ ]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [ ]:
print(np.random.rand())

0.31434729974582354


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
arr3 = np.random.randn(25)
print(arr3)
print(np.mean(arr3))
print(np.std(arr3))

[-0.42794892  0.95754417  0.22399623 -0.6655967  -0.44787891  0.58584418
  0.73363259 -1.00341735  0.64170373  1.04048889  0.46289831 -1.20862321
  0.50134161  0.85654817 -0.90866364  0.31232015 -1.00086251 -0.95007005
 -1.21511354  0.30017671  1.1198221  -1.89102236  0.87485442  1.29776199
  1.91437361]
0.08416438658890453
0.9591245671460156


#### Create the following matrix:

In [ ]:
a = np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1])
b = np.array([[0.1], [0.2], [0.3], [0.4], [0.5], [0.6], [0.7], [0.8], [0.9], [1]])
print(a*b)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.02 0.04 0.06 0.08 0.1  0.12 0.14 0.16 0.18 0.2 ]
 [0.03 0.06 0.09 0.12 0.15 0.18 0.21 0.24 0.27 0.3 ]
 [0.04 0.08 0.12 0.16 0.2  0.24 0.28 0.32 0.36 0.4 ]
 [0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5 ]
 [0.06 0.12 0.18 0.24 0.3  0.36 0.42 0.48 0.54 0.6 ]
 [0.07 0.14 0.21 0.28 0.35 0.42 0.49 0.56 0.63 0.7 ]
 [0.08 0.16 0.24 0.32 0.4  0.48 0.56 0.64 0.72 0.8 ]
 [0.09 0.18 0.27 0.36 0.45 0.54 0.63 0.72 0.81 0.9 ]
 [0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.  ]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
print(np.linspace(0,1,20))

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
print(np.arange(1,26).reshape(5,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
#Using broadcasting
arrA = np.arange(12,23,5)
# print(arrA)
final = arrA[:,None] + np.arange(0,4) #(3,1) + (,4)
print(final)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
print(np.array(20))

20


In [ ]:
print(np.arange(2,13,5).reshape(3,1))

[[ 2]
 [ 7]
 [12]]


In [ ]:
print(np.arange(21,26,1))

[21 22 23 24 25]


In [ ]:
print(np.arange(16,26,1).reshape(2,5))

[[16 17 18 19 20]
 [21 22 23 24 25]]


# Great Job!