# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [4]:
import numpy as np

#### Create an array of 10 zeros

In [6]:
arr = np.full(10,0)

#### Create an array of 10 ones

In [13]:
arr1 = np.full(10,1)

#### Create an array of 10 fives

In [ ]:
arr2 = np.full(10,5)

#### Create an array of the integers from 10 to 50

In [16]:
arr3 = np.arange(10,51)

#### Create an array of all the even integers from 10 to 50

In [19]:
arr4 = np.arange(10,51,2)
print(arr4)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [21]:
arr5 = np.array([[0,1,2],[3,4,5],[6,7,8]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [22]:
arr6 = np.array([[1,0,0],[0,1,0],[0,0,1]])

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### Use NumPy to generate a random number between 0 and 1

In [26]:
from numpy import random
x = random.rand()

0.9077734232214647


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [27]:
arr7=np.random.uniform(-2,2,size=25)

[-0.39144329 -1.89792753  0.88525041 -0.861758    1.13520986 -1.72737432
 -1.68272171  0.91651905  0.97380177 -0.07233815  1.5481985  -1.30207546
 -0.92087456 -1.78263218 -0.90728343 -0.02405763  0.23519624  1.48354596
  1.16313442 -1.83176626 -0.30579281  1.07813966 -0.7570015  -1.35795288
  1.53390608]


#### Create the following matrix:

In [5]:
arr8 = np.linspace(0.01,1,100).reshape(10,10)

#### Create an array of 20 linearly spaced points between 0 and 1:

In [8]:
arr9 = np.round(np.linspace(0.00, 1.00, 20), 8).reshape(4, 5)


[[0.         0.05263158 0.10526316 0.15789474 0.21052632]
 [0.26315789 0.31578947 0.36842105 0.42105263 0.47368421]
 [0.52631579 0.57894737 0.63157895 0.68421053 0.73684211]
 [0.78947368 0.84210526 0.89473684 0.94736842 1.        ]]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [10]:
arr10 = np.round(np.arange(1,26)).reshape(5,5)
print(arr10)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [16]:
arr10[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [18]:
print(arr10[3,4])

20


In [21]:
arr10[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [23]:
arr10[4:5,0:5]

array([[21, 22, 23, 24, 25]])

In [24]:
arr10[3:5,0:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# Great Job!